Repository pallets-eco/flask-caching, pull requests merged in 2022-06, with the labels that each got.

#369 Remove overrides of methods inherited from `cachelib.FileSystemCache`
  CHANGES.rst
  src/flask_caching/backends/filesystemcache.py
  tests/test_backend_cache.py
Labels: bug

#267 add test and docs for caching pluggable view (flask.views.View) classes
  docs/index.rst
  tests/test_view.py
Labels: documentation

#374 release 2.0.0
  CHANGES.rst
  src/flask_caching/__init__.py
Labels: release
